// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.ujob.domain;

import es.uca.iw.ujob.domain.Curriculum;
import es.uca.iw.ujob.domain.CurriculumDataOnDemand;
import es.uca.iw.ujob.domain.CurriculumIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CurriculumIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CurriculumIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CurriculumIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CurriculumIntegrationTest: @Transactional;
    
    @Autowired
    CurriculumDataOnDemand CurriculumIntegrationTest.dod;
    
    @Test
    public void CurriculumIntegrationTest.testCountCurriculums() {
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", dod.getRandomCurriculum());
        long count = Curriculum.countCurriculums();
        Assert.assertTrue("Counter for 'Curriculum' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CurriculumIntegrationTest.testFindCurriculum() {
        Curriculum obj = dod.getRandomCurriculum();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to provide an identifier", id);
        obj = Curriculum.findCurriculum(id);
        Assert.assertNotNull("Find method for 'Curriculum' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Curriculum' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CurriculumIntegrationTest.testFindAllCurriculums() {
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", dod.getRandomCurriculum());
        long count = Curriculum.countCurriculums();
        Assert.assertTrue("Too expensive to perform a find all test for 'Curriculum', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Curriculum> result = Curriculum.findAllCurriculums();
        Assert.assertNotNull("Find all method for 'Curriculum' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Curriculum' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CurriculumIntegrationTest.testFindCurriculumEntries() {
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", dod.getRandomCurriculum());
        long count = Curriculum.countCurriculums();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Curriculum> result = Curriculum.findCurriculumEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Curriculum' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Curriculum' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CurriculumIntegrationTest.testFlush() {
        Curriculum obj = dod.getRandomCurriculum();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to provide an identifier", id);
        obj = Curriculum.findCurriculum(id);
        Assert.assertNotNull("Find method for 'Curriculum' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCurriculum(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Curriculum' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CurriculumIntegrationTest.testMergeUpdate() {
        Curriculum obj = dod.getRandomCurriculum();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to provide an identifier", id);
        obj = Curriculum.findCurriculum(id);
        boolean modified =  dod.modifyCurriculum(obj);
        Integer currentVersion = obj.getVersion();
        Curriculum merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Curriculum' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CurriculumIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", dod.getRandomCurriculum());
        Curriculum obj = dod.getNewTransientCurriculum(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Curriculum' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Curriculum' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CurriculumIntegrationTest.testRemove() {
        Curriculum obj = dod.getRandomCurriculum();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Curriculum' failed to provide an identifier", id);
        obj = Curriculum.findCurriculum(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Curriculum' with identifier '" + id + "'", Curriculum.findCurriculum(id));
    }
    
}
