// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.ujob.domain;

import es.uca.iw.ujob.domain.Localizacion;
import es.uca.iw.ujob.domain.LocalizacionDataOnDemand;
import es.uca.iw.ujob.domain.LocalizacionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LocalizacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LocalizacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LocalizacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LocalizacionIntegrationTest: @Transactional;
    
    @Autowired
    LocalizacionDataOnDemand LocalizacionIntegrationTest.dod;
    
    @Test
    public void LocalizacionIntegrationTest.testCountLocalizacions() {
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", dod.getRandomLocalizacion());
        long count = Localizacion.countLocalizacions();
        Assert.assertTrue("Counter for 'Localizacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LocalizacionIntegrationTest.testFindLocalizacion() {
        Localizacion obj = dod.getRandomLocalizacion();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to provide an identifier", id);
        obj = Localizacion.findLocalizacion(id);
        Assert.assertNotNull("Find method for 'Localizacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Localizacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LocalizacionIntegrationTest.testFindAllLocalizacions() {
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", dod.getRandomLocalizacion());
        long count = Localizacion.countLocalizacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Localizacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Localizacion> result = Localizacion.findAllLocalizacions();
        Assert.assertNotNull("Find all method for 'Localizacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Localizacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LocalizacionIntegrationTest.testFindLocalizacionEntries() {
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", dod.getRandomLocalizacion());
        long count = Localizacion.countLocalizacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Localizacion> result = Localizacion.findLocalizacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Localizacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Localizacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LocalizacionIntegrationTest.testFlush() {
        Localizacion obj = dod.getRandomLocalizacion();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to provide an identifier", id);
        obj = Localizacion.findLocalizacion(id);
        Assert.assertNotNull("Find method for 'Localizacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLocalizacion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Localizacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LocalizacionIntegrationTest.testMergeUpdate() {
        Localizacion obj = dod.getRandomLocalizacion();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to provide an identifier", id);
        obj = Localizacion.findLocalizacion(id);
        boolean modified =  dod.modifyLocalizacion(obj);
        Integer currentVersion = obj.getVersion();
        Localizacion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Localizacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LocalizacionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", dod.getRandomLocalizacion());
        Localizacion obj = dod.getNewTransientLocalizacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Localizacion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Localizacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LocalizacionIntegrationTest.testRemove() {
        Localizacion obj = dod.getRandomLocalizacion();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Localizacion' failed to provide an identifier", id);
        obj = Localizacion.findLocalizacion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Localizacion' with identifier '" + id + "'", Localizacion.findLocalizacion(id));
    }
    
}
