// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.ujob.domain;

import es.uca.iw.ujob.domain.Titulacion;
import es.uca.iw.ujob.domain.TitulacionDataOnDemand;
import es.uca.iw.ujob.domain.TitulacionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TitulacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TitulacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TitulacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TitulacionIntegrationTest: @Transactional;
    
    @Autowired
    TitulacionDataOnDemand TitulacionIntegrationTest.dod;
    
    @Test
    public void TitulacionIntegrationTest.testCountTitulacions() {
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", dod.getRandomTitulacion());
        long count = Titulacion.countTitulacions();
        Assert.assertTrue("Counter for 'Titulacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TitulacionIntegrationTest.testFindTitulacion() {
        Titulacion obj = dod.getRandomTitulacion();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to provide an identifier", id);
        obj = Titulacion.findTitulacion(id);
        Assert.assertNotNull("Find method for 'Titulacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Titulacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TitulacionIntegrationTest.testFindAllTitulacions() {
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", dod.getRandomTitulacion());
        long count = Titulacion.countTitulacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Titulacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Titulacion> result = Titulacion.findAllTitulacions();
        Assert.assertNotNull("Find all method for 'Titulacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Titulacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TitulacionIntegrationTest.testFindTitulacionEntries() {
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", dod.getRandomTitulacion());
        long count = Titulacion.countTitulacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Titulacion> result = Titulacion.findTitulacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Titulacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Titulacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TitulacionIntegrationTest.testFlush() {
        Titulacion obj = dod.getRandomTitulacion();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to provide an identifier", id);
        obj = Titulacion.findTitulacion(id);
        Assert.assertNotNull("Find method for 'Titulacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTitulacion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Titulacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TitulacionIntegrationTest.testMergeUpdate() {
        Titulacion obj = dod.getRandomTitulacion();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to provide an identifier", id);
        obj = Titulacion.findTitulacion(id);
        boolean modified =  dod.modifyTitulacion(obj);
        Integer currentVersion = obj.getVersion();
        Titulacion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Titulacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TitulacionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", dod.getRandomTitulacion());
        Titulacion obj = dod.getNewTransientTitulacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Titulacion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Titulacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TitulacionIntegrationTest.testRemove() {
        Titulacion obj = dod.getRandomTitulacion();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulacion' failed to provide an identifier", id);
        obj = Titulacion.findTitulacion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Titulacion' with identifier '" + id + "'", Titulacion.findTitulacion(id));
    }
    
}
