// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.ujob.domain;

import es.uca.iw.ujob.domain.TitulacionDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TitulacionDataOnDemand_Roo_Configurable {
    
    declare @type: TitulacionDataOnDemand: @Configurable;
    
}
